---
--- @class flora.input.keyboard.keycode
--- 
--- All keycodes taken from the [Love2D Wiki](https://love2d.org/wiki/KeyConstant)
---
local keycode = {
    a = "a",
    b = "b",
    c = "c",
    d = "d",
    e = "e",
    f = "f",
    g = "g",
    h = "h",
    i = "i",
    j = "j",
    k = "k",
    l = "l",
    m = "m",
    n = "n",
    o = "o",
    p = "p",
    q = "q",
    r = "r",
    s = "s",
    t = "t",
    u = "u",
    v = "v",
    w = "w",
    x = "x",
    y = "y",
    z = "z",
    space = "space",

    zero = "0",
    one = "1",
    two = "2",
    three = "3",
    four = "4",
    five = "5",
    six = "6",
    seven = "7",
    eight = "8",
    nine = "9",

    exclamation = "!",
    at = "@",
    hash = "#",
    dollar = "$",
    percent = "%",
    caret = "^",
    ampersand = "&",
    asterisk = "*",
    lparen = "(",
    rparen = ")",
    hyphen = "-",
    underscore = "_",
    plus = "+",
    grave_accent = "`",
    tilde = "~",
    lbrace = "{",
    rbrace = "}",
    vbar = "|",
    lbracket = "[",
    rbracket = "]",
    backslash = "\\",
    colon = ":",
    semicolon = ";",
    apostrophe = "'",
    quote = '"',
    lt = "<",
    gt = ">",
    question = "?",
    comma = ",",
    period = ".",
    slash = "/",

    numpad_0 = "kp0",
    numpad_1 = "kp1",
    numpad_2 = "kp2",
    numpad_3 = "kp3",
    numpad_4 = "kp4",
    numpad_5 = "kp5",
    numpad_6 = "kp6",
    numpad_7 = "kp7",
    numpad_8 = "kp8",
    numpad_9 = "kp9",
    numpad_period = "kp.",
    numpad_divide = "kp/",
    numpad_minus = "kp-",
    numpad_multiply = "kp*",
    numpad_plus = "kp+",
    numpad_enter = "kpenter",

    up = "up",
    down = "down",
    right = "right",
    left = "left",
    home = "home",
    end_ = "end",
    page_up = "pageup",
    page_down = "pagedown",

    insert = "insert",
    backspace = "backspace",
    tab = "tab",
    clear = "clear",
    enter = "enter",
    delete = "delete",

    f1 = "f1",
    f2 = "f2",
    f3 = "f3",
    f4 = "f4",
    f5 = "f5",
    f6 = "f6",
    f7 = "f7",
    f8 = "f8",
    f9 = "f9",
    f10 = "f10",
    f11 = "f11",
    f12 = "f12",
    f13 = "f13",
    f14 = "f14",
    f15 = "f15",
    f16 = "f16",
    f17 = "f17",
    f18 = "f18",

    num_lock = "numlock",
    caps_lock = "capslock",
    scroll_lock = "scrolllock",
    r_shift = "rshift",
    l_shift = "lshift",
    r_ctrl = "rctrl",
    l_ctrl = "lctrl",
    r_alt = "ralt",
    l_alt = "lalt",
    r_gui = "rgui",
    l_gui = "lgui",
    mode = "mode",

    www = "www",
    mail = "mail",
    calculator = "calculator",
    computer = "computer",
    app_search = "appsearch",
    app_home = "apphome",
    app_back = "appback",
    app_forward = "appforward",
    app_refresh = "apprefresh",
    app_bookmarks = "appbookmarks",

    pause = "pause",
    escape = "escape",
    help = "help",
    print_screen = "printscreen",
    sys_req = "sysreq",
    menu = "menu",
    application = "application",
    power = "power",
    currency_unit = "currencyunit",
    undo = "undo",
}
return keycode